
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Qt/6.8.1/Boot2Qt/raspberrypi-armv8/toolchain/sysroots/x86_64-w64-mingw32/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 6.2.9200 - AMD64
...
