// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_Ground_station)
QT_DECLARE_EXTERN_RESOURCE(qmake_Ground_station)
QT_DECLARE_EXTERN_RESOURCE(Ground_station_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Ground_station)

class Ground_stationPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Ground_stationPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Ground_station)
QT_KEEP_RESOURCE(qmlcache_Ground_station)
QT_KEEP_RESOURCE(qmake_Ground_station)
QT_KEEP_RESOURCE(Ground_station_raw_qml_0)
    }
};



#include "Ground_stationplugin_Ground_stationPlugin.moc"
